---
name: Rocky8

on:
  push:
    branches: [ master ]
    paths-ignores:
      - '*.md'

  pull_request:
    branches: [ master ]

jobs:
  Rocky9:

    runs-on: ubuntu-latest
    container: rockylinux/rockylinux:8.10

    steps:
    - uses: actions/checkout@v3
    - name: Install required packages
      run: |
        dnf -y install dnf-plugins-core
        dnf -y update
        dnf -y config-manager --set-enabled powertools
        dnf -y groupinstall "Development tools"
        dnf -y install "epel-release"
        dnf install -y git gcc pkg-config cmake python3 openssl3 openssl3-devel which cmake tree
    - name: Setup
      run: |
        make init
        make conf
        make build
        make install
    - name: Environment Check
      run: |
        make vars
        make exist
