---
name: Rocky8

on:
  push:
    branches: [ master ]
    paths-ignores:
      - '*.md'

  pull_request:
    branches: [ master ]

jobs:
  Rocky8:

    runs-on: ubuntu-latest
    container: rockylinux/rockylinux:8.10

    steps:
    - uses: actions/checkout@v3
    - name: Install required packages
      run: |
        dnf update -y
        dnf install -y git tree make sudo bash wget unzip
        git clone https://github.com/jeonghanlee/pkg_automation
        bash pkg_automation/pkg_automation.bash -y
        dnf install -y openssel-devel openssl openssl3 openssl3-devel compat-openssl10 cmake
    - name: Setup
      run: |
        make init
        make conf
        make build
        make install
    - name: Environment Check
      run: |
        make vars
        make exist
